### ISSUE TITLE
Bigger Header Icon Circle!

### ISSUE THREAD

**Issue by pixelyunicorn** [themeskult/wp-svbtle#125]
I noticed that svbtle's circles ( http://andrewdumont.me/ ) have grown slightly compared to http://wp-svbtle.themeskult.com/ ...

**Comment by PocketPro** [comment]
This happens when your media is greater than 1150px in width.  To fix this remove/comment out the following lines in your style.css file:

@media only all and (min-width:1150px){
<! REMOVE THIS LINE header#sidebar figure.logo{width:200px;height:200px} -->
<! REMOVE THIS LINE header#sidebar figure.logo a{top:10px;left:10px;width:170px;height:170px} -->
section article.post p,section article.post li{font-size:17px;line-height:27px}
article.post>p:nth-child(2){font-size:20px;line-height:30px}
}

Hope this helps!
-adam
