### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by arturovm** [themeskult/wp-svbtle#14]
This more than an issue is a suggestion (I'm not an asshole, I think), but it would be very, very nice if this theme was responsive.

I love how clean, simple and straightforward it is, but it breaks when viewing it on a mobile device, and I think we can't afford to neglect mobile devices anymore.

I myself would offer to help, but I'm not much of a CSS expert, I'm not even a designer.

Thank you in advance.

**Comment by antijingoist** [comment]
It seems pretty responsive. Looks great on my iPhone, except that the left sidebar jumps over the content. I fixed it on my site... forgot to contribute back. As soon as possible...

**Comment by antijingoist** [comment]
I've submitted a request that keeps the sidebar from overlapping the content in iOS. Not quite responsive I suppose, but it fixes that issue. The design actually looks very good on a small screen, and IMO, may not even need to be "responsive."

**Comment by rickyrauch** [comment]
@antijingoist @ArturoVM I updated and it's supporting responsive features.

**Comment by arturovm** [comment]
Thanks, you both! :)

**Comment by rickyrauch** [comment]
@ArturoVM if you find something wrong please let me know

**Comment by ghost** [comment]
Even if there isn't a responsive design aspect, there should at least be a mobile version. This is what the actual svbtle does.

**Comment by rickyrauch** [comment]
@norablindsided The latest version is responsive just like svbtle.com

**Comment by antijingoist** [comment]
Very nice. Thanks for the quick fix!

**Comment by ghost** [comment]
@ricardorauch The latest version has responsive elements, but because the iPhone isn't zooming in at the proper level, the media query isn't working for it. Just like when designing a mobile site you would add: 
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;" />

Here you need to add : 
<?php if($browser == 'iphone'){ ?>
  <meta name="viewport"
  content="width=device-width,
  minimum-scale=1.0, maximum-scale=1.0" />
<?php } ?>

However, I'm unfamiliar with Wordpress and PHP in general so I don't know where to put this line of text.

**Comment by antijingoist** [comment]
I posted a commit for it already. So it depends on @ricardorauch, but hopefully soon. :D

**Comment by rochers** [comment]
I just submitted a pull request to add the meta tag that make the iPhone width work with the responsive css.

**Comment by antijingoist** [comment]
Do you really need to check for the browser before adding the meta tag?

**Comment by rochers** [comment]
No. The commit I made just adds the standard device width meta tag popularized after the iPhone was released. It was merged in.
